if(EXISTS "/home/d/CLionProjects/PlunksnaEngine/tests/test_run-b12d07c_tests.cmake")
  include("/home/d/CLionProjects/PlunksnaEngine/tests/test_run-b12d07c_tests.cmake")
else()
  add_test(test_run_NOT_BUILT-b12d07c test_run_NOT_BUILT-b12d07c)
endif()
